//! Erlang source generation for the uniform, identity-only actor ABI.

use std::fmt::{self, Write};

use crate::Selector;
use crate::dispatch::RuntimeShape;
use crate::ir::{ActorDefinition, Block, IrProgram, LowerError, Operation, SendMode, ValueId};

#[derive(Debug)]
pub enum EmitError {
    InvalidModuleName(String),
    InvalidIr(LowerError),
}

impl fmt::Display for EmitError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidModuleName(name) => write!(f, "invalid Erlang module name: {name:?}"),
            Self::InvalidIr(error) => error.fmt(f),
        }
    }
}
impl std::error::Error for EmitError {}

/// Emit one whole Program. Module names are restricted to portable file names.
pub fn emit_program(program: &IrProgram, module: &str) -> Result<String, EmitError> {
    if !module.starts_with(|c: char| c.is_ascii_lowercase())
        || !module
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_')
    {
        return Err(EmitError::InvalidModuleName(module.into()));
    }
    program.validate().map_err(EmitError::InvalidIr)?;
    let mut output = format!(
        "%% Generated by aspenc. Static adaptation evidence is erased.\n-module({}).\n-export([entry/1]).\n\nentry(_Session) ->\n",
        atom(module)
    );
    block(&mut output, &program.entry, "    ");
    output.push_str("    ok.\n");
    for definition in &program.actors {
        actor(&mut output, definition, module);
    }
    Ok(output)
}

fn atom(value: &str) -> String {
    let mut escaped = String::from("'");
    for character in value.chars() {
        match character {
            '\'' => escaped.push_str("\\'"),
            '\\' => escaped.push_str("\\\\"),
            c if c.is_ascii_graphic() || c == ' ' => escaped.push(c),
            c => write!(escaped, "\\x{{{:x}}}", c as u32).unwrap(),
        }
    }
    escaped.push('\'');
    escaped
}

fn value(id: ValueId) -> String {
    format!("_V{}", id.0)
}

fn selector<T>(selector: &Selector<T>, mut payload: impl FnMut(&T) -> String) -> String {
    match selector {
        Selector::Atomic(name) => format!("{{aspen_atomic, {}}}", atom(name)),
        Selector::Operator { operator, value } => {
            let name = match operator.as_str() {
                "+" => "plus",
                "-" => "minus",
                "*" => "star",
                "/" => "slash",
                name => name,
            };
            format!(
                "{{{}, {}}}",
                atom(&format!("aspen_{name}_operator")),
                payload(value)
            )
        }
        Selector::Keyword(parts) => format!(
            "{{aspen_keyword, {{{}}}, {{{}}}}}",
            parts
                .iter()
                .map(|(name, _)| atom(name))
                .collect::<Vec<_>>()
                .join(", "),
            parts
                .iter()
                .map(|(_, v)| payload(v))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn projection(root: String, path: &[usize]) -> String {
    // Keyword payloads occupy tuple element 3; operator payloads element 2.
    path.iter().fold(root, |root, index| {
        format!("aspen_runtime:project({root}, {index})")
    })
}

fn block(output: &mut String, block: &Block, indent: &str) {
    for instruction in &block.instructions {
        let expression = match &instruction.operation {
            Operation::Check { .. } => continue,
            Operation::Read(binding) => format!("_B{}", binding.0),
            Operation::Selector(s) => selector(s, |id| value(*id)),
            Operation::CreateActor {
                definition,
                captures,
            } => {
                let args = captures
                    .iter()
                    .map(|(_, id)| format!(", {}", value(*id)))
                    .collect::<String>();
                format!(
                    "aspen_runtime:spawn_actor(_Session, fun() -> actor_{}(_Session{args}) end)",
                    definition.0
                )
            }
            Operation::Bind {
                binding,
                value: id,
                path,
            } => {
                writeln!(
                    output,
                    "{indent}_B{} = {},",
                    binding.0,
                    projection(value(*id), path)
                )
                .unwrap();
                continue;
            }
            Operation::Send {
                callee,
                message,
                mode,
                ..
            } => {
                let function = match mode {
                    SendMode::WaitFirst => "call",
                    SendMode::NoReply => "send",
                };
                format!(
                    "aspen_runtime:{function}({}, {})",
                    value(*callee),
                    value(*message)
                )
            }
        };
        match instruction.result {
            Some(id) => writeln!(output, "{indent}{} = {expression},", value(id)).unwrap(),
            None => writeln!(output, "{indent}{expression},").unwrap(),
        }
    }
}

fn pattern(shape: &RuntimeShape, next: &mut usize, guards: &mut Vec<String>) -> String {
    match shape {
        RuntimeShape::Empty => unreachable!("empty clauses are omitted"),
        RuntimeShape::Any => "_".into(),
        RuntimeShape::Actor => {
            let variable = format!("_Shape{}", *next);
            *next += 1;
            guards.push(format!(
                "(is_pid({variable}) orelse (is_tuple({variable}) andalso tuple_size({variable}) =:= 2 andalso element(1, {variable}) =:= aspen_reply andalso is_reference(element(2, {variable}))))"
            ));
            variable
        }
        RuntimeShape::Selector(s) => selector(s, |child| pattern(child, next, guards)),
    }
}

fn actor(output: &mut String, actor: &ActorDefinition, module: &str) {
    let args = actor
        .captures
        .iter()
        .map(|id| format!(", _B{}", id.0))
        .collect::<String>();
    writeln!(output, "\nactor_{}(_Session{args}) ->\n    receive\n        {{aspen_request, _Message, _Reply}} ->\n            case _Message of", actor.id.0).unwrap();
    let mut exhaustive = false;
    for method in actor.methods.iter().filter(|m| !m.dispatch.is_empty()) {
        let mut guards = Vec::new();
        let pattern = pattern(&method.dispatch, &mut 0, &mut guards);
        let guard = if guards.is_empty() {
            String::new()
        } else {
            format!(" when {}", guards.join(" andalso "))
        };
        writeln!(
            output,
            "                {} = {pattern}{guard} ->",
            value(method.message)
        )
        .unwrap();
        for input in &method.inputs {
            writeln!(
                output,
                "                    _B{} = {},",
                input.binding.0,
                projection(value(method.message), &input.path)
            )
            .unwrap();
        }
        if let Some(reply) = method.reply_parameter {
            writeln!(output, "                    _B{} = _Reply,", reply.0).unwrap();
        }
        block(output, &method.body, "                    ");
        output.push_str("                    ok;\n");
        exhaustive |= method.dispatch == RuntimeShape::Any;
    }
    if exhaustive {
        output.truncate(output.len() - 2);
        output.push('\n');
    } else {
        writeln!(
            output,
            "                _ -> erlang:error({{aspen_unmatched, {}, {}, _Message}})",
            atom(module),
            actor.id.0
        )
        .unwrap();
    }
    writeln!(
        output,
        "            end,\n            actor_{}(_Session{args})\n    end.",
        actor.id.0
    )
    .unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Lexer, ir::lower_program, parse, types::check_program};

    fn emit(source: &str) -> String {
        let mut diagnostics = Vec::new();
        let program = parse(Lexer::new(source), &mut diagnostics);
        assert!(diagnostics.is_empty(), "{diagnostics:?}");
        emit_program(
            &lower_program(&check_program(&program).unwrap()).unwrap(),
            "test_program",
        )
        .unwrap()
    }

    #[test]
    fn recursive_dispatch_and_captures_are_executable_not_evidence() {
        let code = emit("let x = {}. { def outer: (#inner: ({} y)) => x. y. }.");
        assert!(
            code.contains("{aspen_keyword, {'outer'}, {{aspen_keyword, {'inner'}, {_Shape0}}}}")
        );
        assert!(code.contains("is_pid(_Shape0) orelse"));
        assert!(code.contains("=:= aspen_reply"));
        assert!(code.contains("aspen_runtime:project(aspen_runtime:project("));
        assert!(code.contains("actor_1(_Session, _B0)"));
        assert!(!code.contains("Adaptation"));
    }

    #[test]
    fn replies_wait_even_when_discarded_and_bottom_clauses_are_absent() {
        let code = emit("let a = { def go -> #ok => ^ #ok. def no: (never x) => x. }. a go.");
        assert!(code.contains("aspen_runtime:call("));
        assert!(code.contains("aspen_runtime:send("));
        assert!(!code.contains("'no'"));
    }

    #[test]
    fn broad_receiver_and_empty_actor_have_valid_case_endings() {
        let broad = emit("{ def (x) => x. }.");
        assert!(broad.contains("ok\n            end,"));
        assert!(!broad.contains("aspen_unmatched"));
        assert!(emit("{}.").contains("aspen_unmatched"));
    }

    #[test]
    fn names_are_escaped_and_module_names_are_validated() {
        assert_eq!(atom("a'\\\n"), "'a\\'\\\\\\x{a}'");
        assert_eq!(atom("\u{e5}"), "'\\x{e5}'");
        let program = IrProgram {
            entry: Block::default(),
            actors: vec![],
        };
        assert!(emit_program(&program, "bad-name").is_err());
        assert!(emit_program(&program, "").is_err());
    }
}
