//! Erlang source generation for the uniform, identity-only actor ABI.

use std::{
    collections::BTreeSet,
    fmt::{self, Write},
};

use crate::Selector;
use crate::dispatch::RuntimeShape;
use crate::ir::{
    ActorDefinition, BindingId, Block, IrProgram, LowerError, Operation, SendMode, ValueId,
};

#[derive(Debug)]
pub enum EmitError {
    InvalidModuleName(String),
    InvalidIr(LowerError),
}

impl fmt::Display for EmitError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidModuleName(name) => write!(f, "invalid Erlang module name: {name:?}"),
            Self::InvalidIr(error) => error.fmt(f),
        }
    }
}
impl std::error::Error for EmitError {}

/// Emit one whole Program. Module names are restricted to portable file names.
pub fn emit_program(program: &IrProgram, module: &str) -> Result<String, EmitError> {
    if !module.starts_with(|c: char| c.is_ascii_lowercase())
        || !module
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_')
    {
        return Err(EmitError::InvalidModuleName(module.into()));
    }
    program.validate().map_err(EmitError::InvalidIr)?;
    let mut output = format!(
        "%% Generated by aspenc. Static adaptation evidence is erased.\n-module({}).\n-export([entry/1]).\n\nentry(_Session) ->\n",
        atom(module)
    );
    if !program.globals.instructions.is_empty() {
        output.push_str("    aspen_runtime:initialize_globals(_Session, fun() ->\n");
        block(&mut output, &program.globals, "        ", &[], program);
        output.push_str("        ok\n    end),\n");
    }
    block(&mut output, &program.entry, "    ", &[], program);
    output.push_str("    ok.\n");
    for definition in &program.actors {
        actor(&mut output, definition, module, program);
    }
    Ok(output)
}

fn atom(value: &str) -> String {
    let mut escaped = String::from("'");
    for character in value.chars() {
        match character {
            '\'' => escaped.push_str("\\'"),
            '\\' => escaped.push_str("\\\\"),
            c if c.is_ascii_graphic() || c == ' ' => escaped.push(c),
            c => write!(escaped, "\\x{{{:x}}}", c as u32).unwrap(),
        }
    }
    escaped.push('\'');
    escaped
}

fn value(id: ValueId) -> String {
    format!("_V{}", id.0)
}

fn selector<T>(selector: &Selector<T>, mut payload: impl FnMut(&T) -> String) -> String {
    match selector {
        Selector::Atomic(name) => format!("{{aspen_atomic, {}}}", atom(name)),
        Selector::Operator { operator, value } => {
            let name = match operator.as_str() {
                "+" => "plus",
                "-" => "minus",
                "*" => "star",
                "/" => "slash",
                name => name,
            };
            format!(
                "{{{}, {}}}",
                atom(&format!("aspen_{name}_operator")),
                payload(value)
            )
        }
        Selector::Keyword(parts) => format!(
            "{{aspen_keyword, {{{}}}, {{{}}}}}",
            parts
                .iter()
                .map(|(name, _)| atom(name))
                .collect::<Vec<_>>()
                .join(", "),
            parts
                .iter()
                .map(|(_, v)| payload(v))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn projection(root: String, path: &[usize]) -> String {
    // Keyword payloads occupy tuple element 3; operator payloads element 2.
    path.iter().fold(root, |root, index| {
        format!("aspen_runtime:project({root}, {index})")
    })
}

// Only values needed after the call belong to its suspended continuation.
// Loop captures remain live even when the current method no longer uses them.
fn continuation_roots(block: &Block, captures: &[BindingId]) -> Vec<Vec<String>> {
    let mut live: BTreeSet<String> = captures.iter().map(|id| format!("_B{}", id.0)).collect();
    let mut roots = vec![Vec::new(); block.instructions.len()];
    for (index, instruction) in block.instructions.iter().enumerate().rev() {
        if let Some(id) = instruction.result {
            live.remove(&value(id));
        }
        roots[index] = live.iter().cloned().collect();
        match &instruction.operation {
            Operation::Global(name) => {
                live.insert(format!("{{aspen_global, {}}}", atom(name)));
            }
            Operation::DefineGlobal { value: id, .. } => {
                live.insert(value(*id));
            }
            Operation::Read(id) => {
                live.insert(format!("_B{}", id.0));
            }
            Operation::Selector(selector) => {
                live.extend(selector.values().into_iter().map(|id| value(*id)));
            }
            Operation::CreateActor { captures, .. } => {
                live.extend(captures.iter().map(|(_, id)| value(*id)));
            }
            Operation::Bind {
                binding, value: id, ..
            } => {
                live.remove(&format!("_B{}", binding.0));
                live.insert(value(*id));
            }
            Operation::Send {
                callee, message, ..
            } => {
                live.insert(value(*callee));
                live.insert(value(*message));
            }
            Operation::Check { .. }
            | Operation::Syscall
            | Operation::Int(_)
            | Operation::Float(_)
            | Operation::String(_) => {}
        }
    }
    roots
}

fn block(
    output: &mut String,
    block: &Block,
    indent: &str,
    captures: &[BindingId],
    program: &IrProgram,
) {
    let roots = continuation_roots(block, captures);
    for (index, instruction) in block.instructions.iter().enumerate() {
        let expression = match &instruction.operation {
            Operation::Global(name) => format!("aspen_runtime:global(_Session, {})", atom(name)),
            Operation::DefineGlobal { name, value: id } => format!(
                "aspen_runtime:define_global(_Session, {}, {})",
                atom(name),
                value(*id)
            ),
            Operation::Syscall => "aspen_runtime:syscall(_Session)".into(),
            Operation::Check { .. } => continue,
            Operation::Read(binding) => format!("_B{}", binding.0),
            Operation::Int(value) => value.to_string(),
            Operation::Float(value) => value.to_string(),
            // Numeric bytes avoid Erlang source encoding and escaping ambiguities.
            Operation::String(value) => format!(
                "<<{}>>",
                value
                    .as_bytes()
                    .iter()
                    .map(u8::to_string)
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Operation::Selector(s) => selector(s, |id| value(*id)),
            Operation::CreateActor {
                definition,
                captures,
            } => {
                let args = captures
                    .iter()
                    .map(|(_, id)| format!(", {}", value(*id)))
                    .collect::<String>();
                let globals = program
                    .actors
                    .iter()
                    .find(|a| a.id == *definition)
                    .unwrap()
                    .globals
                    .iter()
                    .map(|name| atom(name))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(
                    "aspen_runtime:spawn_actor(_Session, fun() -> actor_{}(_Session{args}) end, [{globals}])",
                    definition.0
                )
            }
            Operation::Bind {
                binding,
                value: id,
                path,
            } => {
                writeln!(
                    output,
                    "{indent}_B{} = {},",
                    binding.0,
                    projection(value(*id), path)
                )
                .unwrap();
                continue;
            }
            Operation::Send {
                callee,
                message,
                mode,
                ..
            } => {
                let function = match mode {
                    SendMode::WaitFirst => "call",
                    SendMode::NoReply => "send",
                };
                let continuation = if *mode == SendMode::WaitFirst {
                    format!(", [{}]", roots[index].join(", "))
                } else {
                    String::new()
                };
                format!(
                    "aspen_runtime:{function}({}, {}{continuation})",
                    value(*callee),
                    value(*message)
                )
            }
        };
        match instruction.result {
            Some(id) => writeln!(output, "{indent}{} = {expression},", value(id)).unwrap(),
            None => writeln!(output, "{indent}{expression},").unwrap(),
        }
    }
}

fn pattern(
    shape: &RuntimeShape,
    next: &mut usize,
    guards: &mut Vec<String>,
    strings: &mut Vec<String>,
) -> String {
    match shape {
        RuntimeShape::Empty => unreachable!("empty clauses are omitted"),
        RuntimeShape::Any => "_".into(),
        RuntimeShape::Actor => {
            let variable = format!("_Shape{}", *next);
            *next += 1;
            guards.push(format!(
                "(is_pid({variable}) orelse (is_tuple({variable}) andalso tuple_size({variable}) =:= 2 andalso element(1, {variable}) =:= aspen_reply andalso is_reference(element(2, {variable}))))"
            ));
            variable
        }
        RuntimeShape::Selector(s) => selector(s, |child| pattern(child, next, guards, strings)),
        family => {
            let variable = format!("_Shape{}", *next);
            *next += 1;
            let atomic = format!(
                "(is_tuple({variable}) andalso tuple_size({variable}) =:= 2 andalso element(1, {variable}) =:= aspen_atomic)"
            );
            let operator = format!(
                "(is_tuple({variable}) andalso tuple_size({variable}) =:= 2 andalso (element(1, {variable}) =:= aspen_plus_operator orelse element(1, {variable}) =:= aspen_minus_operator orelse element(1, {variable}) =:= aspen_star_operator orelse element(1, {variable}) =:= aspen_slash_operator))"
            );
            let keyword = format!(
                "(is_tuple({variable}) andalso tuple_size({variable}) =:= 3 andalso element(1, {variable}) =:= aspen_keyword)"
            );
            guards.push(match family {
                RuntimeShape::String => {
                    strings.push(variable.clone());
                    format!("is_binary({variable})")
                }
                RuntimeShape::Bytes => format!("is_binary({variable})"),
                RuntimeShape::Int => format!("is_integer({variable})"),
                RuntimeShape::Float => format!("is_float({variable})"),
                RuntimeShape::Atom => atomic,
                RuntimeShape::OpTagged => operator,
                RuntimeShape::KeywordTagged => keyword,
                RuntimeShape::SelectorFamily => {
                    format!("({atomic} orelse {operator} orelse {keyword})")
                }
                _ => unreachable!(),
            });
            variable
        }
    }
}

fn actor(output: &mut String, actor: &ActorDefinition, module: &str, program: &IrProgram) {
    let args = actor
        .captures
        .iter()
        .map(|id| format!(", _B{}", id.0))
        .collect::<String>();
    let captures = actor
        .captures
        .iter()
        .map(|id| format!("_B{}", id.0))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(output, "\nactor_{}(_Session{args}) ->\n    {{aspen_request, _Message, _Reply}} = aspen_runtime:receive_request(_Session, [{captures}]),\n            case _Message of", actor.id.0).unwrap();
    let mut exhaustive = false;
    for method in actor.methods.iter().filter(|m| !m.dispatch.is_empty()) {
        let mut guards = Vec::new();
        let mut strings = Vec::new();
        let pattern = pattern(&method.dispatch, &mut 0, &mut guards, &mut strings);
        let guard = if guards.is_empty() {
            String::new()
        } else {
            format!(" when {}", guards.join(" andalso "))
        };
        writeln!(
            output,
            "                {} = {pattern}{guard} ->",
            value(method.message)
        )
        .unwrap();
        // UTF-8 validation is not an Erlang guard BIF. Disjoint receiver shapes
        // ensure no other clause could accept a failed string refinement.
        if !strings.is_empty() {
            let valid = strings
                .iter()
                .map(|v| format!("aspen_runtime:is_string({v})"))
                .collect::<Vec<_>>()
                .join(" andalso ");
            writeln!(output, "                    case {valid} of true -> ok; false -> erlang:error({{aspen_unmatched, {}, {}, _Message}}) end,", atom(module), actor.id.0).unwrap();
        }
        for input in &method.inputs {
            writeln!(
                output,
                "                    _B{} = {},",
                input.binding.0,
                projection(value(method.message), &input.path)
            )
            .unwrap();
        }
        if let Some(reply) = method.reply_parameter {
            writeln!(output, "                    _B{} = _Reply,", reply.0).unwrap();
        }
        block(
            output,
            &method.body,
            "                    ",
            &actor.captures,
            program,
        );
        output.push_str("                    ok;\n");
        exhaustive |= method.dispatch == RuntimeShape::Any;
    }
    if exhaustive {
        output.truncate(output.len() - 2);
        output.push('\n');
    } else {
        writeln!(
            output,
            "                _ -> erlang:error({{aspen_unmatched, {}, {}, _Message}})",
            atom(module),
            actor.id.0
        )
        .unwrap();
    }
    writeln!(
        output,
        "            end,\n            actor_{}(_Session{args}).",
        actor.id.0
    )
    .unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Lexer, ir::lower_program, parse, types::check_program};

    fn emit(source: &str) -> String {
        let mut diagnostics = Vec::new();
        let program = parse(Lexer::new(source), &mut diagnostics);
        assert!(diagnostics.is_empty(), "{diagnostics:?}");
        emit_program(
            &lower_program(&check_program(&program).unwrap()).unwrap(),
            "test_program",
        )
        .unwrap()
    }

    #[test]
    fn recursive_dispatch_and_captures_are_executable_not_evidence() {
        let code = emit("let x = {}. { def outer: (#inner: ({ ready } y)) => x. y. }.");
        assert!(
            code.contains("{aspen_keyword, {'outer'}, {{aspen_keyword, {'inner'}, {_Shape0}}}}")
        );
        assert!(code.contains("is_pid(_Shape0) orelse"));
        assert!(code.contains("=:= aspen_reply"));
        assert!(code.contains("aspen_runtime:project(aspen_runtime:project("));
        assert!(code.contains("actor_1(_Session, _B0)"));
        assert!(!code.contains("Adaptation"));
    }

    #[test]
    fn replies_wait_even_when_discarded_and_bottom_clauses_are_absent() {
        let code = emit("let a = { def go -> #ok => ^ #ok. def no: (never x) => x. }. a go.");
        assert!(code.contains("aspen_runtime:call("));
        assert!(code.contains("aspen_runtime:send("));
        assert!(!code.contains("'no'"));
    }

    #[test]
    fn suspended_calls_publish_only_live_continuation_terms() {
        let mut diagnostics = Vec::new();
        let program = parse(
            Lexer::new(
                "let dead = {}. let live = {}. let service = { def go -> {} => }. \
             service go. live.",
            ),
            &mut diagnostics,
        );
        assert!(diagnostics.is_empty());
        let ir = lower_program(&check_program(&program).unwrap()).unwrap();
        let roots = continuation_roots(&ir.entry, &[]);
        let call = ir
            .entry
            .instructions
            .iter()
            .position(|instruction| {
                matches!(
                    instruction.operation,
                    Operation::Send {
                        mode: SendMode::WaitFirst,
                        ..
                    }
                )
            })
            .unwrap();
        assert_eq!(roots[call], ["_B1"]);
        let code = emit_program(&ir, "live_test").unwrap();
        assert!(code.contains(", [_B1])"));
        assert!(code.contains("aspen_runtime:receive_request(_Session, [])"));

        let code =
            emit("let captured = {}. { def go: ({ go -> {} } service) => service go. captured. }.");
        assert!(code.contains("aspen_runtime:receive_request(_Session, [_B0])"));
        assert!(
            code.lines()
                .any(|line| line.contains("aspen_runtime:call(") && line.ends_with(", [_B0]),"))
        );
    }

    #[test]
    fn broad_receiver_and_empty_actor_have_valid_case_endings() {
        let broad = emit("{ def (x) => x. }.");
        assert!(broad.contains("ok\n            end,"));
        assert!(!broad.contains("aspen_unmatched"));
        let top = emit("{ def ({} x) => x. }.");
        assert!(!top.contains("is_pid"));
        assert!(!top.contains("aspen_unmatched"));
        assert!(emit("{}.").contains("aspen_unmatched"));
    }

    #[test]
    fn primitive_families_emit_runtime_guards() {
        for (ty, guard) in [
            ("string", "is_binary(_Shape0)"),
            ("int", "is_integer(_Shape0)"),
            ("float", "is_float(_Shape0)"),
            ("atom", "=:= aspen_atomic"),
            ("optagged", "=:= aspen_plus_operator"),
            ("keywordtagged", "=:= aspen_keyword"),
            ("selector", "=:= aspen_keyword"),
        ] {
            assert!(emit(&format!("{{ def ({ty} x) => }}.")).contains(guard));
        }
    }

    #[test]
    fn names_are_escaped_and_module_names_are_validated() {
        assert_eq!(atom("a'\\\n"), "'a\\'\\\\\\x{a}'");
        assert_eq!(atom("\u{e5}"), "'\\x{e5}'");
        let program = IrProgram {
            globals: Block::default(),
            entry: Block::default(),
            actors: vec![],
        };
        assert!(emit_program(&program, "bad-name").is_err());
        assert!(emit_program(&program, "").is_err());
    }
}
